language: cpp
sudo: false

git:
  depth: 1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - zip
      - unzip
      - clang
      - make
      - autoconf2.13
      - yasm
      - libgtk2.0-dev
      - libglib2.0-dev
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - libasound2-dev
      - libiw-dev
      - libxt-dev
      - mesa-common-dev
      - libgstreamer0.10-dev
      - libgstreamer-plugins-base0.10-dev
      - libpulse-dev
      - m4
      - flex

script:
  - bash build/travis_ci/travis_ci.sh build
after_success:
  - bash build/travis_ci/travis_ci.sh upload_build
after_script:
  - bash build/travis_ci/travis_ci.sh upload_logs
